;==========================================================
;
; Preventive Maintenance Scheduler
;
; Version : 1.0
; Build   : 001
;
; Designed and created by
; Jenerwin Camba
;
;==========================================================

[platformio]

default_envs = nano_esp32

;==========================================================

[env:nano_esp32]

platform = espressif32

board = arduino_nano_esp32

framework = arduino

monitor_speed = 115200

upload_speed = 921600

build_flags =
    -std=gnu++17
    -Wall
    -Wextra

lib_deps =
    adafruit/RTClib @ ^2.1.4
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

lib_ldf_mode = deep+

check_skip_packages = yes